/**
 * Inline blocklist of the most commonly leaked passwords. Used to reject
 * trivially-guessable credentials at registration / password-change time.
 *
 * This list is intentionally tiny (~200 entries) so it stays in memory with
 * zero cost. It covers the long tail of credential-stuffing tries and the
 * brunt of "Password123!" style attempts. For a stronger guarantee, layer a
 * full HIBP k-anonymity check on top later — but doing so requires a
 * network call per registration, which is overkill for now.
 *
 * Source: condensed top entries from the SecLists `10-million-password-list-top-*`
 * (public domain) plus common app-themed variants (chess1234, chesspass, …).
 */

const COMMON_PASSWORDS = new Set<string>([
  "123456",
  "123456789",
  "12345678",
  "1234567",
  "1234567890",
  "12345",
  "1234",
  "111111",
  "11111111",
  "121212",
  "112233",
  "123123",
  "131313",
  "232323",
  "654321",
  "666666",
  "000000",
  "00000000",
  "098765",
  "1qaz2wsx",
  "qwerty",
  "qwerty123",
  "qwertyuiop",
  "qwerty1",
  "qweasd",
  "asdfgh",
  "asdfghjkl",
  "zxcvbnm",
  "zxcvbn",
  "abcd1234",
  "abc123",
  "abc12345",
  "1q2w3e4r",
  "1q2w3e",
  "1qazxsw2",
  "password",
  "password1",
  "password123",
  "password!",
  "pass1234",
  "passw0rd",
  "p@ssw0rd",
  "p@ssword",
  "letmein",
  "letmein1",
  "iloveyou",
  "iloveyou1",
  "monkey",
  "monkey1",
  "dragon",
  "dragon1",
  "shadow",
  "master",
  "superman",
  "batman",
  "trustno1",
  "welcome",
  "welcome1",
  "welcome123",
  "admin",
  "admin1",
  "admin123",
  "administrator",
  "root",
  "toor",
  "test",
  "test123",
  "test1234",
  "user",
  "user1",
  "guest",
  "login",
  "changeme",
  "default",
  "secret",
  "secret1",
  "money",
  "starwars",
  "computer",
  "internet",
  "google",
  "facebook",
  "michael",
  "jennifer",
  "jessica",
  "ashley",
  "amanda",
  "matthew",
  "andrew",
  "nicole",
  "joshua",
  "daniel",
  "anthony",
  "robert",
  "thomas",
  "charlie",
  "tigger",
  "sunshine",
  "princess",
  "football",
  "baseball",
  "basketball",
  "soccer",
  "hockey",
  "jordan",
  "harley",
  "ranger",
  "buster",
  "freedom",
  "michelle",
  "ginger",
  "hammer",
  "summer",
  "winter",
  "autumn",
  "spring",
  "killer",
  "george",
  "asshole",
  "fuckyou",
  "fuckyou1",
  "fuckme",
  "bitches",
  "hello",
  "hello1",
  "hello123",
  "helloworld",
  "loveme",
  "newpass",
  "passme",
  "pass123",
  "qwer1234",
  "asdf1234",
  "Aa123456",
  "Abc12345",
  "Password1",
  "Password123",
  "Welcome1",
  "Welcome123",
  "Qwerty123",
  "qwerty12",
  "letmein123",
  "iloveu",
  "ilove",
  "ilovegod",
  "iloveyou123",
  "test1",
  "guest1",
  "guest123",
  "demo",
  "demo123",
  // Chess-themed obvious ones — bots scrape app branding for guesses.
  "chess",
  "chess1",
  "chess12",
  "chess123",
  "chess1234",
  "chesspass",
  "chesspassword",
  "chessmaster",
  "stockfish",
  "magnus",
  "carlsen",
  "magnus1",
  "kasparov",
  "fischer",
  "kingdom",
  "kingside",
  "queenside",
  "checkmate",
  "checkmate1",
  "checkmate123",
  "chessfinder",
  "chessfinderpro",
  "finder",
  "finder1",
  "finder123",
]);

/** True if `pw` is a known trivially-guessable password. Case-insensitive. */
export function isCommonPassword(pw: string): boolean {
  if (!pw) return true;
  const lower = pw.toLowerCase();
  if (COMMON_PASSWORDS.has(lower)) return true;
  // Many leaks add trailing digits — catch e.g. "password!1" / "password2025".
  const stripped = lower.replace(/[!@#$%^&*._\-+=?\d]+$/g, "");
  if (stripped.length >= 4 && COMMON_PASSWORDS.has(stripped)) return true;
  return false;
}
